version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=stationSki
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  app:
    container_name: app
    depends_on:
      - mysqldb
    build: ./
    image: medazizali/alpine:abc
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url":"jdbc:mysql://mysqldb:3306/stationSki?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true",
            "spring.datasource.username" : "root",
            "spring.datasource.password" :  "",
            "spring.jpa.show-sql" : "true",
            "spring.jpa.hibernate.ddl-auto" : "update",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect", 
            "management.endpoints.web.exposure.include" : "*" ,
            "management.endpoint.health.show-details" : "always",
            "management.endpoint.metrics.enabled" : "true" 
            
           }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: